/*
 * © Bart Kampers
 */
package bka.swing;

import bka.swing.popup.*;
import java.awt.*;
import java.awt.event.*;


public class Demo extends javax.swing.JFrame {

 
    public Demo() {
        initComponents();
        String osName = System.getProperty("os.name");
        if (osName.contains("Mac")) {
            label.setToolTipText("<html>One finger click to alter text<br>Two finger click to alter color</html>");
        }
        else {
            label.setToolTipText("<html>Click left to alter text<br>Click right to alter color</html>");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        popupDemoPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setText("Click to alter text");
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_mouseClicked(evt);
            }
        });

        javax.swing.GroupLayout popupDemoPanelLayout = new javax.swing.GroupLayout(popupDemoPanel);
        popupDemoPanel.setLayout(popupDemoPanelLayout);
        popupDemoPanelLayout.setHorizontalGroup(
            popupDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupDemoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        popupDemoPanelLayout.setVerticalGroup(
            popupDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupDemoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Popup", popupDemoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void label_mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_mouseClicked
        Rectangle bounds;
        switch (evt.getButton()) {
            case MouseEvent.BUTTON1:
                bounds = label.getBounds();
                bounds.height = 25;
                PopupControl.show(popupDemoPanel, new TextFieldPopupModel(bounds, label.getText(), label::setText));
                break;
            case MouseEvent.BUTTON3:
                bounds = new Rectangle(label.getLocation(), new Dimension(700, 250));
                PopupControl.show(popupDemoPanel, new ColorChooserPopupModel(bounds, label.getForeground(), label::setForeground));
                break;
        }
    }//GEN-LAST:event_label_mouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Demo().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JPanel popupDemoPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
