/*
 * © Bart Kampers
 */
package bka.swing;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


public class Demo extends javax.swing.JFrame {

 
    public Demo() {
        initComponents();
        label.setToolTipText("<html>Click left to alter text<br>Click right to alter color</html>");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        popupDemoPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setText("Click to alter text");
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout popupDemoPanelLayout = new javax.swing.GroupLayout(popupDemoPanel);
        popupDemoPanel.setLayout(popupDemoPanelLayout);
        popupDemoPanelLayout.setHorizontalGroup(
            popupDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupDemoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        popupDemoPanelLayout.setVerticalGroup(
            popupDemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupDemoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Popup", popupDemoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseClicked
        switch (evt.getButton()) {
            case MouseEvent.BUTTON1: 
                Popup.show(popupDemoPanel, new LabelTextPopupModel());
                break;
            case MouseEvent.BUTTON3:
                Popup.show(popupDemoPanel, new ColorPopupModel());
                break;
        }
    }//GEN-LAST:event_labelMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Demo().setVisible(true);
        });
    }
    
    
    private class LabelTextPopupModel extends TextFieldPopupModel {

        @Override
        public Rectangle getBounds() {
            Rectangle bounds = label.getBounds();
            bounds.height = 25;
            return bounds;
        }
        
        @Override
        public String getInitialValue() {
            return label.getText();
        }

        @Override
        public void applyNewValue() {
            label.setText(getText());
        }
        
    }
    
    
    private class ColorPopupModel implements Popup.Model<Color> {

        @Override
        public Component getComponent() {
            colorChooser.setColor(getInitialValue());
            return colorChooser;
        }

        @Override
        public Rectangle getBounds() {
            Rectangle bounds = label.getBounds();
            bounds.height = 400;
            return bounds;
        }

        @Override
        public void bindListener(Popup.ModelListener listener) {
            colorChooser.getSelectionModel().addChangeListener(evt -> listener.apply());
        }

        @Override
        public Color getInitialValue() {
            return label.getForeground();
        }

        @Override
        public void applyNewValue() {
            label.setForeground(colorChooser.getColor());
        }
        
        private final JColorChooser colorChooser = new JColorChooser();
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JPanel popupDemoPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
